services:
  client:
    container_name: habit_app_client
    build: ./client
    image: debug_client
    ports: 
      - 5050:5050
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: habit_app_api
    ports: 
      - 3001:3001
    environment: 
      - PGUSER=habitapp
      - PGHOST=db
      - PGPASSWORD=habitapp_pass
      - PGDATABASE=habits
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: habit_app_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=habits
      - POSTGRES_USER=habitapp
      - POSTGRES_PASSWORD=habitapp_pass
volumes:
  dbdata:
networks: 
  default:
    name: debug_api
