services:
  api:
    container_name: habit_test_api
    environment:
      - PGUSER=habitapp
      - PGHOST=db
      - PGPASSWORD=habitapp_pass
      - PGDATABASE=habits
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: habit_test_db
    volumes:
      - 'dbdata:/var/lib/mongodb/data'
      - './db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro'
    environment:
      - MONGO_INITDB_DATABASE=habitsapp
      - MONGO_INITDB_ROOT_PASSWORD=habitapp-pass
volumes:
  test_db:
networks:
  default:
    name: debug_test
