services:
  client:
    container_name: habit_app_client
    build: ./client
    image: habits_client
    ports:
      - 5050:5050
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: ['http-server']
  api:
    container_name: habit_app_api
    ports:
      - 3001:3001
    environment:
      - DB_CONNECTION=mongodb://habitsapp-admin:habitapp-pass@db:27017
      - DB_NAME=habitsapp
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: habit_app_db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=habitsapp-admin
      - MONGO_INITDB_DATABASE=habits_app_user
      - MONGO_INITDB_ROOT_PASSWORD=habitapp-pass
    volumes:
      - 'dbdata:/var/lib/mongodb/data'
      - './db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro'
volumes:
  dbdata:
networks:
  default:
    name: habits_api
