services:
  api:
    container_name: habit_test_api
    image: mongo:latest
    environment:
      - DB_CONNECTION=mongodb://habitsapp-admin:habitapp-pass@db:27017
      - MONGO_INITDB_HOST=db
      - MONGO_INITDB_DATABASE=habitsapp_test
      - MONGO_INITDB_ROOT_USERNAME=habitsapp-admin
      - MONGO_INITDB_ROOT_PASSWORD=habitapp-pass
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"
    tty: true
  db:
    container_name: habit_test_db
    image: mongo:latest
    volumes:
      - 'dbdata:/var/lib/mongodb/data'
      - './db/seed.js:/docker-entrypoint-initdb.d/seed.js:ro'
    environment:
      - MONGO_INITDB_DATABASE=habitsapp_test
      - MONGO_INITDB_ROOT_USERNAME=habitsapp-admin
      - MONGO_INITDB_ROOT_PASSWORD=habitapp-pass
volumes:
  dbdata:
networks:
  default:
    name: habit_test
